### PR TITLE
fix: remove oci:// prefix from registry host when login

### LINKED ISSUE #8: Failed to push to OCI registry
Got this error:
```
[11:08:51 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: helm push <redacted> <redacted url>
Error: scheme prefix missing from remote (e.g. "oci://")
```

with helm:
```
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

### PR DESCRIPTION
**Pull request by alita1991**
Closes #8

### CODE REVIEW

**Comment by nflaig** [comment]
Do you have a reference on why this is all of the sudden needed with helm version > 3.10?

This solution feels a bit hacky to me. Based on the helm version the registry needs to be defined in a different format with and without `oci://` prtefix. Maybe it would be better to handle this internally so there is no difference on how the registry URI needs to be set. See https://github.com/nflaig/semantic-release-helm/issues/8#issuecomment-1489241000

Maybe @lsoica can take a look as well and give feedback

**Comment by alita1991** [comment]
Hi @nflaig 

You can read about this at https://helm.sh/docs/topics/registries/

This issue is also similar with mine https://github.com/helm/helm/issues/10814

**Comment by nflaig** [comment]
thanks for the links, looks like helm just doesn't care about following semver

I really think this should be implemented differently by updating the [push command](https://helm.sh/docs/topics/registries/#the-push-subcommand) else once users upgrade to helm versions >= 3.8.0 their setup will break because they will have their `registry` URI set without `oci://` prefix.

image

**Comment by alita1991** [comment]
@nflaig the change is only required when we log in to the registry, after this, we just have to use the registry defined in the config.
Do you think the change I made will impact also other commands like push?

**Comment by nflaig** [comment]
I main concern is just that once others users upgrade to helm version 3.8.0 their setup will break because they did not explicity specify `oci://` in their registry URI

**Comment by alita1991** [comment]
Make sense, give me some time to update the code, will let you know

**Comment by nflaig** [comment]
Do you by any chance know if helm push breaks in version 3.7.0 if you specify the `oci://` prefix? If that is not the case we can just always add it on push, and just for the sake of it always remove it on login

**Comment by alita1991** [comment]
Hi, I found this post https://blog.devgenius.io/helm-3-7-changes-to-oci-registry-16f2887e0704
I believe this answers your question, it will not break in 3.7.0, we are safe.

File: lib/publish.js [hunk 1]
```diff
@@ -76,6 +76,7 @@ async function publishChartToRegistry(configPath, registry, name, version) {
                 );
 
                 const chartArchive = stdout.split(":")[1].trim();
+                registry = registry.includes("oci://") ? registry : "oci://".concat(registry)
```
Comment (nflaig) [inline lib/publish.js:79]: `registry.includes("oci://")` will never be `true`, to be honest I liked stripping it off on the login operation because some people might specify it based on the updated helm docs

prefer not to use concat for appending string

```suggestion
                registry = registry.includes("oci://") ? registry : "oci://" + registry
```

or 

```suggestion
                registry = registry.includes("oci://") ? registry : `oci://${registry}`
```

**Review by nflaig — CHANGES_REQUESTED** [review]

**Comment by alita1991** [comment]
If I modify the pluginConfig.registry in the verifyConditions.js default function, will remain modified in the other scripts as well? like publish.js?

**Comment by alita1991** [comment]
@nflaig please check, I made more changes

File: lib/publish.js [hunk 2]
```diff
@@ -76,6 +76,7 @@ async function publishChartToRegistry(configPath, registry, name, version) {
                 );
 
                 const chartArchive = stdout.split(":")[1].trim();
+                registry = `oci://${registry}`
```
Comment (nflaig) [inline lib/publish.js:79]: now we break setups where the `registry` starts with `oci://`

File: lib/publish.js (hunk 1 above)
Comment (alita1991) [reply lib/publish.js]: done

**Comment by nflaig** [comment]
> If I modify the pluginConfig.registry in the verifyConditions.js default function, will remain modified in the other scripts as well? like publish.js?

No string are not mutated like this in javascript, else the `.split` would be a issue already

File: lib/publish.js (hunk 2 above)
Comment (alita1991) [reply lib/publish.js]: reverted to the original commit

**Comment by alita1991** [comment]
@nflaig I believe it should be fine now

- if oci:// is provided, removed before login and not added because is already in place
- if oci:// is not provided, nothing to be removed before login and added before we do the push

File: lib/publish.js [hunk 3]
```diff
@@ -76,6 +76,7 @@ async function publishChartToRegistry(configPath, registry, name, version) {
                 );
 
                 const chartArchive = stdout.split(":")[1].trim();
+                registry = registry.startsWith("oci://") ? registry : `oci://${registry}`
```
Comment (nflaig) [inline lib/publish.js:79]:
```suggestion
                registry = registry.startsWith("oci://") ? registry : `oci://${registry}`;
```

**Review by nflaig — APPROVED** [review]
lgtm, thanks @alita1991 for fixing this!

**Comment by nflaig** [comment]
Published [semantic-release-helm3@2.4.2](https://www.npmjs.com/package/semantic-release-helm3/v/2.4.2)

**Comment by Ruchira-R** [comment]
Helm version : version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}



`Error: scheme prefix missing from remote (e.g. "oci://")`

This is still an issue. I am pushing my Helm Charts to Amazon ECR using oci://

Example : 
`helm push test-helm-chart.tgz oci://<AWS Account>.dkr.ecr.<region>.amazonaws.com/`
